/*
Copyright The Kubernetes Authors.

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// NodeHealthListerExpansion allows custom methods to be added to
// NodeHealthLister.
type NodeHealthListerExpansion interface{}

// NodeHealthNamespaceListerExpansion allows custom methods to be added to
// NodeHealthNamespaceLister.
type NodeHealthNamespaceListerExpansion interface{}
