/*
Copyright The Kubernetes Authors.

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "../pkg/apis/nodehealth/v1alpha1"
	scheme "../pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodeHealthsGetter has a method to return a NodeHealthInterface.
// A group's client should implement this interface.
type NodeHealthsGetter interface {
	NodeHealths(namespace string) NodeHealthInterface
}

// NodeHealthInterface has methods to work with NodeHealth resources.
type NodeHealthInterface interface {
	Create(ctx context.Context, nodeHealth *v1alpha1.NodeHealth, opts v1.CreateOptions) (*v1alpha1.NodeHealth, error)
	Update(ctx context.Context, nodeHealth *v1alpha1.NodeHealth, opts v1.UpdateOptions) (*v1alpha1.NodeHealth, error)
	UpdateStatus(ctx context.Context, nodeHealth *v1alpha1.NodeHealth, opts v1.UpdateOptions) (*v1alpha1.NodeHealth, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NodeHealth, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NodeHealthList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeHealth, err error)
	NodeHealthExpansion
}

// nodeHealths implements NodeHealthInterface
type nodeHealths struct {
	client rest.Interface
	ns     string
}

// newNodeHealths returns a NodeHealths
func newNodeHealths(c *ComputeV1alpha1Client, namespace string) *nodeHealths {
	return &nodeHealths{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodeHealth, and returns the corresponding nodeHealth object, and an error if there is any.
func (c *nodeHealths) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NodeHealth, err error) {
	result = &v1alpha1.NodeHealth{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodehealths").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeHealths that match those selectors.
func (c *nodeHealths) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NodeHealthList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NodeHealthList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodehealths").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeHealths.
func (c *nodeHealths) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodehealths").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nodeHealth and creates it.  Returns the server's representation of the nodeHealth, and an error, if there is any.
func (c *nodeHealths) Create(ctx context.Context, nodeHealth *v1alpha1.NodeHealth, opts v1.CreateOptions) (result *v1alpha1.NodeHealth, err error) {
	result = &v1alpha1.NodeHealth{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodehealths").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeHealth).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nodeHealth and updates it. Returns the server's representation of the nodeHealth, and an error, if there is any.
func (c *nodeHealths) Update(ctx context.Context, nodeHealth *v1alpha1.NodeHealth, opts v1.UpdateOptions) (result *v1alpha1.NodeHealth, err error) {
	result = &v1alpha1.NodeHealth{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodehealths").
		Name(nodeHealth.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeHealth).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *nodeHealths) UpdateStatus(ctx context.Context, nodeHealth *v1alpha1.NodeHealth, opts v1.UpdateOptions) (result *v1alpha1.NodeHealth, err error) {
	result = &v1alpha1.NodeHealth{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodehealths").
		Name(nodeHealth.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeHealth).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nodeHealth and deletes it. Returns an error if one occurs.
func (c *nodeHealths) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodehealths").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeHealths) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodehealths").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nodeHealth.
func (c *nodeHealths) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeHealth, err error) {
	result = &v1alpha1.NodeHealth{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodehealths").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
